-- CREATE TABLE quest (
--     questID int(5) NOT NULL AUTO_INCREMENT,
--     questShortName varchar(25) NOT NULL UNIQUE,
--     questName varchar(50) NOT NULL,
--     UNIQUE (questID, questShortName)
-- );

-- CREATE TABLE stage (
--     stageID int(5) NOT NULL AUTO_INCREMENT,
--     questShortName varchar(25) NOT NULL,
--     progress int(3),
--     logText text,
--     rewardExp int,
--     finishesQuest boolean,
--     UNIQUE KEY (stageID),
--     FOREIGN KEY (questShortName) REFERENCES quest(questShortName)
-- );

-- CREATE TABLE monster (
--     monsterID int(5) NOT NULL AUTO_INCREMENT,
--     monsterName varchar(50) NOT NULL,
--     monsterFriendlyName varchar(50) NOT NULL,
--     maxHP int,
--     maxAP int,
--     monsterClass char(25),
--     droplistID char(50),
--     attackCost int,
--     attackChance int,
--     criticalSkill int,
--     criticalMultiplier decimal(2,1),
--     blockChance int,
--     damageResistance int,
--     unique boolean,
--     phraseID varchar(50),
--     movementAggressionType varhcar(50),
--     faction varchar(50),
--     UNIQUE KEY (monsterID)
-- )